inventory-syncronization: 
    scheduler-cron: "0 0/4 0 ? * * *"
    timezone: "America/Monterrey"
    file-directory: "/inventory"
    fixed-file: "inventory.csv"    
    processed-files-path: "files-proccessed"
    new-files-path: "new-inventory-files"
    batch-size: "100"
smtp:   
    host: "sandbox.smtp.mailtrap.io"
    port: "2525"
    fromEmail: "mulesoft-notification-dev@jaem.com"
    toEmail: "jose.escobar.macias@hotmail.com,ananda.sankar@salesforce.com"
    retries: "3"
    ms-between-retries: "30000"
    readResponseSecondsTimeout: "180"
    writeResponseSecoundsTimeout: "180"
    secondsTimeout: "180" 
    errorSubject: "ERROR Notification - IMMEDIATE Attention Required in '[muleApp]' Application"    
    warningSubject: "WARNING Notification - Attention Required in '[muleApp]' Application"
    infoSubject: "INFO Notification - Attention Required in '[muleApp]' Application"   