inventory-syncronization: 
    scheduler-cron: "0 0 4 ? * * *"
    timezone: "America/Monterrey"
    file-directory: "/inventory"
    fixed-file: "inventory.csv"    
    processed-files-path: "files-proccessed"
    new-files-path: "new-inventory-files"
    batch-size: "2000"
smtp:   
    host: "smtp.mailersend.net"    
    port: "587"
    fromEmail: "mulesoft-notification-dev@trial-yzkq340m516ld796.mlsender.net"
    toEmail: "jose.escobar.macias@hotmail.com"
    retries: "3"
    ms-between-retries: "30000"
    readResponseSecondsTimeout: "180"
    writeResponseSecoundsTimeout: "180"
    secondsTimeout: "180" 
    errorSubject: "ERROR Notification - IMMEDIATE Attention Required in '[muleApp]' Application"    
    warningSubject: "WARNING Notification - Attention Required in '[muleApp]' Application"
    infoSubject: "INFO Notification - Attention Required in '[muleApp]' Application"
    user: "MS_2uIT8j@trial-yzkq340m516ld796.mlsender.net"
    
sftp:
  host: "mulesofttestjaemsftp.blob.core.windows.net"
  port: "22"
  user: "mulesofttestjaemsftp.jaem"
  working-directory: "/inventory"